services:
  neo4j:
    image: neo4j:5.13.0
    container_name: iot-neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/iot-password-2024
      - NEO4J_PLUGINS=["apoc"]
    volumes:
      - neo4j_data:/data
    networks:
      - iot-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "iot-password-2024", "RETURN 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: iot-backend
    ports:
      - "0.0.0.0:8000:8000"
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=iot-password-2024
      - OLLAMA_HOST=http://host.docker.internal:11434
      - CHROMA_PERSIST_DIR=/app/chroma_db
    volumes:
      - ./backend/app:/app/app
      - ./backend/app/data:/app/app/data
      - chroma_data:/app/chroma_db
    depends_on:
      neo4j:
        condition: service_healthy
    networks:
      - iot-network
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  neo4j_data:
  chroma_data:

networks:
  iot-network:
    driver: bridge